version: '2.3'

services:
  golang:
    image: cosmtrek/air
    container_name: ${COMPOSE_PROJECT_NAME}_golang
    # working_dir value has to be the same of mapped volume
    working_dir: /yao3060/learn-golang
    ports:
      - ${HTTP_PORT}:8000
    env_file: .env
    environment:
      - DEBUG=1
    depends_on:
      - cache
      - mysql
    volumes:
      - ./src/:/yao3060/learn-golang/

  mysql:
    image: mysql:8
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - ${ADMINER_HTTP_PORT}:8080

  cache:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: always
    command: --loglevel verbose

volumes:
  db:
